module.exports = {
  "introduction": [
    {
      "type": "autogenerated",
      "dirName": "introduction"
    }
  ],
  "tmpl": [
    {
      "type": "doc",
      "id": "tmpl/sidbar_doc",
      "label": "Doc Type"
    },
    {
      type: 'link',
      label: 'Link Type 外链',
      href: 'https://facebook.com',
    },
    {
      type: 'link',
      label: 'Link Type 内链',
      href: '/',
    },
  ]
};